name 'example42-iptables'
version '3.0.0-beta'

author        'Alessandro Franceschi & Dolf Schimmel - Freeaqingme'
license       'Apache2'
project_page  'https://www.github.com/stdmod'
source        'https://github.com/stdmod/puppet-iptables'
summary       'Puppet module for Iptables'
description   'This module installs and manages iptables. Supports both IPv4 and IPv6. Provides defined types for managing chains, tables and rules.'
dependency    'example42/puppi', '>=2.0.0'
dependency    'ripienaar/concat', '>=0.0.1'
dependency    'puppetlabs/stdlib'
